// REA/atividade_previa/angular/my-imc/src/app/app.component.ts
import { Component } from '@angular/core';
import { IMC } from './classes/IMC';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent {
  imc = new IMC(0, 0);

  calcularIMC() {
    const res = (<HTMLInputElement>document.querySelector('#resultado'));
    res.textContent = this.imc._getIMC();
  }
  atualizaPeso(event) {
    this.imc.setPeso(+event.target.value)
    this.calcularIMC();
  }

  atualizaAltura(event) {
    this.imc.setAltura(+event.target.value);
    this.calcularIMC();
  }
}

<header>
  <div class="container">
    <div class="card-panel">
      <p class="row">Calcule o seu IMC: </p>
    </div>
    <div>
      <div>
          <app-input-label 
            label="Digite o seu Peso (Kg):" 
            customId="peso"
            (input) = "atualizaPeso($event)"
          ></app-input-label>
      </div>
      <div>
        <app-input-label 
          label="Digite o sua Altura (metros):" 
          customId="altura"
          (input) = "atualizaAltura($event)"
          ></app-input-label>
      </div>
    </div>
    <app-result-label></app-result-label>
  </div>
</header>

// REA/atividade_previa/vue/my-imc/src/App.vue
<template>
  <div id="app">
    <div class="container">
        <div class="card-panel">
          <p class="row">Calcule o seu IMC: </p>
        </div>
        <div>
          <div>
            <input-label label="Digite o seu Peso (Kg):" id="peso" :onInputChange="atualizarPeso"> </input-label>
          </div>
          <div>
            <input-label label="Digite o sua Altura (metros):" id="altura" :onInputChange="atualizarAltura"> </input-label>
          </div>
        </div>
        <div class="card-panel">
          <span id="resultado">Favor preencher o seu PESO e ALTURA para calcular o IMC.</span>
        </div>
      </div>
  </div>
</template>

<script>
import InputLabel from './components/shared/InputLabel.vue';
import {IMC} from './classes/IMC.js';

export default {
  components: { InputLabel },
  name: 'app',
  data () {
    return {
      imc: new IMC(0, 0),
      peso: 0,
      altura: 0,
    }
  },
  methods:{
    atualizarPeso: function(event){
      this.imc = new IMC(+event.target.value, this.altura);
      this.peso = +event.target.value;
      this.calcularIMC();
    },
    atualizarAltura: function(event){
      this.imc = new IMC(this.peso, +event.target.value)
      this.altura = +event.target.value;
      this.calcularIMC();
    },
    calcularIMC: function() {
      const res = this.$el.querySelector('#resultado');
      res.textContent = this.imc._getIMC();
    }
  }
}
</script>
